# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: 'rocker/r-ver:3.6.2'

steps:
- script: Rscript -e 'R.version'
  displayName: 'R Version'

- script: Rscript -e 'dir.create("library"); install.packages("devtools", lib = "library", repos="https://mran.microsoft.com/snapshot/2019-09-20/"); library("devtools", lib.loc = "library"); devtools::check()'
  displayName: 'Package Check'
