# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

container: 'rocker/tidyverse:latest'

steps:
- script: Rscript -e 'R.version'
  displayName: 'R Version'

- script: Rscript -e 'library("devtools"); devtools::check()'
  displayName: 'Package Check'
